agentName: mongodDB
agentType: integration
title: 'MongoDB monitoring integration'
metaDescription: 'Install the mongoDB integration'
introFilePath: 'src/install/mongodb/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'

steps:
  - filePath: 'src/install/mongodb/appInfo.mdx'
  - filePath: 'src/install/mongodb/default-requirements.mdx'
  - filePath: 'src/install/mongodb/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/mongodb/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/mongodb/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'
  - filePath: 'src/install/mongodb/default-configuration.mdx'
  - filePath: 'src/install/mongodb/find-data.mdx'
whatsNextFilePath: 'src/install/mongodb/whatsNext.mdx'
